### ISSUE TITLE
Remove notification delay setting + title change

### ISSUE THREAD

**Issue by jancborchardt** [youtify/youtify#106]
It seems like the current notifications only display inside Youtify, which appears to be a bit useless since notifications are mostly useful when actually seen outside the app. Are there plans to do Chrome native notifications (is there an open browser notification standard / also something for Firefox yet)?
At the moment, Chrome calls attention to the tab because of the notifications, as if something important happened (new message, error) as a next song playing isn’t particularly out of order, this should be removed.

Also, the current setting of notification time is not something people should need to set. The real setting would be an on/off toggle for notifications.

**Comment by pthulin** [comment]
We already have webkit notificaitons but I agree on removing the window title change and the notificaiton delay setting. I'll assign myself to this issue.
