### ISSUE TITLE
logo needs to be updated

### ISSUE THREAD

**Issue by jancborchardt** [youtify/youtify#108]
At the moment it’s just text, and »Yo« as favicon & sticker doesn’t look particularly exciting. I have some experience with logo design so I’ll see if I have ideas on this.

**Comment by pthulin** [comment]
+1, would be cool to see other ideas for the logo.

**Comment by jancborchardt** [comment]
I played around with the thought of combining the Y with a play symbol some time ago already. Today I made a quick sketch:
![logo](http://i.imgur.com/dEmEI.png)

It doesn’t feel like too much of a play button at the moment, but I’m sure it’s just missing a bit of visual design. It definitely makes for a distinctive play button shape (as seen in the sketches in issue #179).

**Comment by kallux** [comment]
f17f10b842e511c332dd51960327108fe92f39ae closes this. See www.youtify.com/logo for more examples on how to use the new logo and banner

**Comment by jancborchardt** [comment]
Neat! Can you put up the logo as SVG as well?

(I also want to try how it looks without border & filling because that looks a bit derpy.)

**Comment by kallux** [comment]
Sorry don't have an SVG. It is all made with shapes in PS. I tried without the borders but it didn't look good (too skinny). Also I kind of like how the external circle becomes a part of the soundwaves.

**Comment by jancborchardt** [comment]
You also need to update the logo in the [Chrome webstore app](https://chrome.google.com/webstore/detail/ceimdjnelbadcaempefhdpdhdokpnbho).

**Comment by pthulin** [comment]
I updated the screenshot and logo, however the logo looks crap when it's uploaded for some reason. I think it's because Google scales it according to the specs here https://developers.google.com/chrome/web-store/docs/images

... I fiddled around with different sizes and backgrounds without getting around the scaling :/

**Comment by jancborchardt** [comment]
Oh also, the logo on the Github org (on Gravatar) is still the old one: https://github.com/youtify

**Comment by kallux** [comment]
Thank you. It's fixed now.
