### ISSUE TITLE
public stats

### ISSUE THREAD

**Issue by jancborchardt** [youtify/youtify#111]
There should be public stats, with Piwik for example. It works pretty nice for us on [ownCloud](http://demo.owncloud.org/stats). It also is a good first start on quantitative user testing.

**Comment by pthulin** [comment]
A start is up at http://www.youtify.com/stats

Also I want to have a discussion around what stats are interesting. For me, I only care about how many active users we have and where they are coming from (both geographically and traffic source). Also I want to know what music they are searching for, for which our toplist/landing page is probably the best place to display this on.

**Comment by jancborchardt** [comment]
The high discrepancy between Playlist subscriptions & Follow relations and Users & Playlists is already interesting. We need to make it easier to discover similar stuff. Similar people, similar playlists. Submitted that as separate Issue #120.

**Comment by pthulin** [comment]
The stats page is good for now, closing this issue.

**Comment by jancborchardt** [comment]
I just checked out the stats page again. Is it really 4238 registered users? And 3406 playlists seems quite much also. Is there a page to view all these playlists?

Especially weird is the graph, which shows that there are about 50 active users on average, but »Users logged in since last week« says 514. Maybe the graph is just confusing.
