### ISSUE TITLE
Youtube video quality

### ISSUE THREAD

**Issue by kallux** [youtify/youtify#122]
The youtube player seems to override our quality setting and set it automatically from the iframe size. This means that we have to make a workaround. Load in hidden fullscreen if quality==HD720.

**Comment by apuint** [comment]
You can set playback quality at onStateChange handler:

```
'onStateChange': function(event) { 
    if (event.data == YT.PlayerState.BUFFERING)
        event.target.setPlaybackQuality('hd720');
}
```

**Comment by pthulin** [comment]
Hey hjuntune, worked like a charm. Thanks!
