### ISSUE TITLE
Change icons to webfont

### ISSUE THREAD

**Issue by kallux** [youtify/youtify#147]
Replace as many icons/images as possible to a webfont so it looks good on a retina display. See [Entypo](http://www.entypo.com/), [Web Symbols](http://www.justbenicestudio.com/studio/websymbols/), [Pictos](http://pictos.cc/font/), [Raphaël Icon-Set](http://icons.marekventur.de/) or [Peculiar](http://lucianmarin.com/peculiar/). Try to find one set that covers all if possible. Also this will greatly improve the overall style of the page.

**Comment by jancborchardt** [comment]
Or rather use SVG with PNG fallback, that’s how we do it with [ownCloud http://owncloud.org] from the start.
