### ISSUE TITLE
include artist name in search results

### ISSUE THREAD

**Issue by jancborchardt** [youtify/youtify#181]
SoundCloud search results rarely contain the artist name. Reason being that unlike Youtube, where everyone uploads songs, on SoundCloud usually has original content with the artists themselves upload the music to their account.

As a solution, for SoundCloud songs there should be the artist name included in the list.

Additionally, the artist name and song name should be visually distinguished in the list. Even in Youtube that can be found out, it’s mostly the part before the : or -
The artist name should be bolded with the song title following after some spacing:
**Artist**&nbsp;&nbsp;song title

**Comment by pthulin** [comment]
Closed in https://github.com/youtify/youtify/commit/bb3471c5406854418f4f64a79c6f10f9ef4afe33
