### ISSUE TITLE
hide »Play Queue« and »Search Results« when empty

### ISSUE THREAD

**Issue by jancborchardt** [youtify/youtify#189]
Initially, or when you never search something, the »Search Results« entry in the navigation just leads to a blank page. Instead, that navigation element should just be hidden.
Similar with the »Play Queue« – initially that is empty so it should be hidden.

Slightly related, regarding the Play Queue: when you just play a playlist that shouldn’t be displayed in the Play Queue, because that just duplicates the playlist.

**Comment by pthulin** [comment]
I think we should completely remove "Search Results" from the left menu. iTunes and Spotify doesn't show it there.

**Comment by jancborchardt** [comment]
Yeah, good call. The results can be shown once, and the text in the box is preserved anyway.

**Comment by kallux** [comment]
Closed with the new 320design
