### ISSUE TITLE
Integrate Youku

### ISSUE THREAD

**Issue by pthulin** [youtify/youtify#209]
Youku is the Chinese equivalent of YouTube.

http://dev.youku.com/
http://music.youku.com/

This would probably require us getting a Chinese speaking person on the team.

**Comment by ZiyaoWei** [comment]
Hi pthulin,

As a Chinese who is pretty interested in this app, I agree this could be a good idea, so this issue attracts my attention.
However, on the dev page you referenced here it says:

优酷Open API现阶段只对合作方开放，不对个人开发者开放，您需要申请合作方ID（partnerID / pid）才能使用

Translation: Youku Open API at this moment only opens to "partners", not to individual developers, you need to apply for the partnerID to use the API.

Is there still any plans on this and could this be a potential blocker?

Thanks for the great app!

Ziyao

**Comment by kallux** [comment]
Ziyao: Youku is still an interesting option to have as a backend. Right now, my time to spend on Youtify is limited, but in a couple of weeks that will change. I will then have a look and see if we can use the API without a partnerID, but if that doesn't work, could you help us communicate with Youku?

**Comment by ZiyaoWei** [comment]
That will be a pleasure, just tell me and I'll go ahead.

**Comment by kallux** [comment]
I requested the partner ID and did a test implementation with Youku's JS API but, their API is really buggy and doesn't even support basic events like telling us if the video is paused or playing. Also they do weird stuff with the browser functions and variables like changing window.console. My conclusion is that the Youku API is probably enough if you want to embed a video on your blog, but for us, in it's current state, it is unusable. :(

**Comment by rav124** [comment]
Hi Kallux, I'm trying to get a Partner ID for Youku. Can you help guide me how you went about to request this from Youku. Thanks
