### ISSUE TITLE
play Youtube playlist in Youtify

### ISSUE THREAD

**Issue by jancborchardt** [youtify/youtify#221]
Much like you can view user profiles from Youtube and play all their songs, it should be possible to search or view Youtube playlists in Youtify.

**Comment by kallux** [comment]
In early versions of Youtify we had that feature. But since we didn't use it and many playlists contained blocked videos, it was replaced with searching Youtify playlists. I am going to close this issue for now and if we really feel that we need it again in the future we can reopen it.
