### ISSUE TITLE
current song is paused when clicking on followed artist

### ISSUE THREAD

**Issue by jancborchardt** [youtify/youtify#224]
1. I play a song from a playlist.
2. I want to browse around my stuff so I click through some other playlists.
3. In the list I click an artist from Soundcloud I subscribed to.
4. The track pauses.

No idea why that happens. Can you reproduce it? I’m currently on Chromium and only have Soundcloud artists in my list, so no idea if it happens with Youtube artists also.

**Comment by kallux** [comment]
Is this still happening? I cannot reproduce it on Chrome under Windows 7.

**Comment by jancborchardt** [comment]
Nope, everything's fine now.
