### ISSUE TITLE
shuffle setting isn’t remembered

### ISSUE THREAD

**Issue by jancborchardt** [youtify/youtify#225]
Currently, every time I start Youtify, playlists start playing in order. Instead of needing to set them back to shuffle as soon as I want to start listening, the shuffle on/off setting should be remembered for each playlist. As I likely want to hear some playlists in shuffle, and others in order, for instance if it’s an album. In any case, the last setting should just be remembered.

**Comment by kallux** [comment]
This setting used to be per playlist but we removed it and made it global after much discussion. The main point from this discussion (and feedback from users) was that it was confusing since no other player works that way.
