### ISSUE TITLE
permalinks to Soundcloud broken

### ISSUE THREAD

**Issue by jancborchardt** [youtify/youtify#229]
When I click on the Soundcloud logo on a song, I get to an address like http://www.youtify.com/soundcloud_id_to_permalink?id=10626332 (why not a direct link?)

The problem is that this link does not work. I get an error page:

Sorry an unknown error has occured.

Please try the following:
- Reload the page
- Send us a tweet

**Comment by kallux** [comment]
Thanks, I'll take a look at it. With soundcloud, all we get is an ID and not the SEO friendly link. So we have to make a separate request to soundcloud to actually get the link.
