### ISSUE TITLE
[Chrome Extension] Background Player + Multimedia Keys support

### ISSUE THREAD

**Issue by julianxhokaxhiu** [youtify/youtify#235]
Hi guys,

I came across your service and I really love it. But since I was a spotify/grooveshark user I was used to play/pause, go to the next track or to the back one using multimedia keys of my keyboard. Actually, It wasn't a native function but it was deployed with an extension for Chrome (I developed myself, https://chrome.google.com/webstore/detail/grooveshark-mediakeys-rel/jaicdopiaemahiofpemoljckbebcpcjm).

I can develop it in 5 min for you and it's ok if you like this. But I would like to make it one step beyond (but I have to see if Chrome Enables this) which is a "Youtify" button in the upper left corner of Chrome (next to the settings button) which with a help of a popup, let the user to search for a song, and play it.

The mediakeys functions may have to work with it and the popup doesn't have to been always shown (see it like a background player). If it could be done it would be cool!

Tell me what you think and if I can help you. Greets,
Julian

//EDIT
Gotcha! Found it! The background player could be done, as this extension is already doing it :)
https://chrome.google.com/webstore/detail/cobalt-media-player/lomkdjfdigkefccckbebcanbmndlfjjk

**Comment by kallux** [comment]
It sounds really nice! Media keys ftw.
Since the search is all client side, maybe that should wait, if you don't really want to implement it =) Actually, I don't know how long it will take before we have time to rewrite the search, so go ahead.

But I say go ahead with the extension! And thanks! I'm really looking forward to it.

**Comment by julianxhokaxhiu** [comment]
Great! This weekend I'll do it and I'll commit into my own repo. When it's done I'll link it here. May I publish it under Chrome Extensions gallery too?

**Comment by kallux** [comment]
Sorry for not getting back to you. Of course you can publish it in the Chrome Extensions gallery.
