### ISSUE TITLE
Default volume

### ISSUE THREAD

**Issue by MOZGIII** [youtify/youtify#243]
Volume is 100% by default, which, for me, lead to very loud first sounds...

The volume should be persistent across the app sessions with the app within one machine or browser, so I advice using some kind of clientside storage (localstorage, cookies, or sth).

I could try implementing this if you'd accept the pull requst.

**Comment by pthulin** [comment]
I think having the volume in localStorage so that it's per device is a good idea.

I know we considered it before, but decided against it for some reason. Now I find myself often wishing it was as you describe.

If you make a pull request I think we would happily pull it in.

**Comment by MOZGIII** [comment]
It will take me some time to get with the code and build system used, so it will not be fast. It seems like a few lines of code here and there, but, for me it'll require a whole dev env setup. I can do it, but it might be slow, and right now I'm a bit busy. So, are you waiting, or you'll try to implement it by yourself?

**Comment by pthulin** [comment]
No stress, just ping us when you have something ready :)

**Comment by MOZGIII** [comment]
Nice, ok then.

**Comment by MOZGIII** [comment]
So, it is done. Anything wrong?

**Comment by pthulin** [comment]
Merged your pull request, thanks.

**Comment by MOZGIII** [comment]
Nice to see it deployed! :)

**Comment by pthulin** [comment]
Yup, seems to work fine :)
