### ISSUE TITLE
Add Open Graph meta data

### ISSUE THREAD

**Issue by melpomene** [youtify/youtify#31]
Add Open Graph meta data to allow content sharing sites (i.e Facebook and Goole Plus) to embedd videos from Youtify. 

https://developers.facebook.com/docs/opengraph/

There is a problem that the video will be embedded with a link to Youtube instead of Youtify. If this is not solvable maby it is preferable to show album-art next to the link with Open Graph instead. (Images could be collected from the Linko API).

**Comment by kallux** [comment]
The og:video link now resolves to youtube, we'll have to push and see if it works like we want to.
