### ISSUE TITLE
Last.fm integration

### ISSUE THREAD

**Issue by jonindiepassion** [youtify/youtify#32]
Please suppport last.fm scrobbling. 
Spotify does.

**Comment by kallux** [comment]
#Suggested implementation:
- Create a database on appengine containing caching functionality for last.fm. See section 4.4 on [last.fm tos](http://www.lastfm.se/api/tos)
- Map url to handle requests
- Add to fatbar

**Comment by pthulin** [comment]
What would be in the FatBar? Isn't scrobbling just a background thing? Anyway, good idea, I'm moving this to v11.

**Comment by jancborchardt** [comment]
By the way, I told Elloe from [Libre.fm](http://libre.fm) about Youtify. It’s a free & open alternative to last.fm, it would be interesting to integrate with them as well.

**Comment by auroranockert** [comment]
Implemented this at #wowhack, try it in the wowhack branch.
