### ISSUE TITLE
Drag n drop from related to playlist

### ISSUE THREAD

**Issue by kallux** [youtify/youtify#33]
Be able to drag a video from the related videos in the fatbar directly to the playlist in the right column.

**Comment by pthulin** [comment]
The playlist in the right column?

**Comment by kallux** [comment]
Yep.
Use case: 
You are listening to a song and sees a related song that you like. The playlist items are already showing. It's natural to be able to just drag the related song anywhere into the other playlist items and position it directly where you want to.

**Comment by pthulin** [comment]
Ah OK agree, I didn't get the "playlist to the right" part but I understand we're talking about the main list area. Moving this to v11.

**Comment by pthulin** [comment]
We don't have related anymore.
