### ISSUE TITLE
Feature: mixcloud integration

### ISSUE THREAD

**Issue by olleolleolle** [youtify/youtify#93]
I want to be doing this, since a family member has such high output on that service, and I can't make myself go on there and fix it.

I forked the repo and will give this a try real soon, so if you want to work on it with me give me a shout.

Ciao!

**Comment by kallux** [comment]
This is something that we want to integrate as well, but unfortunately it seems like their API doesn't support streaming or even a chromeless player. :(

http://www.mixcloud.com/developers/documentation/

**Comment by olleolleolle** [comment]
Thanks for your careful reading, good, then I'll close this issue as a non-starter.
