### ISSUE TITLE
Add XSPF-playlist support

### ISSUE THREAD

**Issue by voxpelli** [youtify/youtify#94]
Would be cool if one could add external playlists and export Youtify playlists in XSPF-format. It's supported by eg. Last.fm: http://www.last.fm/api/playlists

**Comment by kallux** [comment]
The xspf file could be outputted if you add /xspf at the end of the playlist url.
IE: http://www.youtify.com/users/xxx/playlists/xxx/xspf

http://en.wikipedia.org/wiki/Xspf
