### ISSUE TITLE
Drag a video to the last position does not work

### ISSUE THREAD

**Issue by pthulin** [youtify/youtify#96]
Previously we had a drag event when a video was dragged to the playlist element (container). The video would then get positioned last in the playlist. This does not work anymore.

**Comment by jancborchardt** [comment]
Yep. Dropping to reorder is also a bit weird because you need to drop something onto the track where you want the other one to be. Rather, the space inbetween the tracks should be highlighted, and the other songs already moved around – just like in Chrome (and Firefox?) with tabs.
